---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: testing1
    pull: never
    image: golang:1.12-alpine
    commands:
      - echo "test1"
      - echo "test2"

#  - name: publish
#    image: plugins/gcr
#    settings:
#      repo: project/foo
#      tags: latest
#      json_key:
#        from_secret: google_credentials
#
#  - name: build-image
#    image: plugins/docker
#    settings:
#      repo: weweadsl/helloworld
#      target: production
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password
#      tags: ${DRONE_TAG}

  - name: testing2
    pull: always
    image: ubuntu
    commands:
      - echo "test11"
      - echo "test222"

image_pull_secrets:
  - dockerconfigjson
