---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: testing1
    pull: always
    image: golang:1.12-alpine
    commands:
      - echo "test1"
      - echo "test2"

  - name: build-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "hub.docker.com/weweadsl/helloworld"
      tags: ${DRONE_TAG}
      registry: "hub.docker.com"

  - name: testing2
    pull: always
    image: ubuntu
    commands:
      - echo "test11"
      - echo "test222"

image_pull_secrets:
  - dockerconfigjson
