---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/weweadsl/HelloForGo

steps:
  - name: testing1
    pull: never
    image: golang
    environment:
      TEXT: 123
    commands:
      - echo "test drone"
      - echo $TEST

  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    environment:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      TESTUSER:
        from_secret: docker_username
    commands:
      - echo $TESTUSER
      - go build  -o app

  - name: publish-image
    image: plugins/docker
    dockerfile: docker/Dockerfile
    environment:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    settings:
      repo: weweadsl/helloworld
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
#      target: production
#      tags: latest
      auto_tag: true

  - name: testing2
    pull: never
    image: ubuntu
    commands:
      - echo "test111"
      - echo "test222"
      - echo $TEST

image_pull_secrets:
  - dockerconfigjson
