---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/weweadsl/HelloForGo

steps:
  - name: testing1
    pull: never
    image: golang
    environment:
      TEXT: 123
    commands:
      - echo "test drone"
      - echo $TEST
      - echo $DRONE_TAG
      - echo $DRONE_REPO
      - echo $DRONE_REPO_NAME

  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    environment:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build  -o app
      -
  - name: upx-pack
    pull: always
    image: alpine
    commands:
      - apk add --no-cache upx
      - upx -9 app

  - name: publish-image
    image: plugins/docker
    settings:
      repo: weweadsl/helloworld
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
#      auto_tag: true

  - name: testing2
    pull: never
    image: ubuntu
    commands:
      - echo "test111"
      - echo "test222"
      - echo $TEST

image_pull_secrets:
  - dockerconfigjson
