---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: testing1
  pull: always
  image: golang:1.12-alpine
  commands:
  - echo "test1"
  - echo "test2"

- name: testing2
  pull: always
  image: ubuntu
  commands:
  - echo "test11"
  - echo "test22"

image_pull_secrets:
- dockerconfigjson
