---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

workspace:
  base: /go

steps:
  - name: testing1
    pull: never
    image: golang
    environment:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go get github.com/joho/godotenv
      - echo "test1"
      - echo "test22"
      - echo $TEST

  - name: build-image
    image: plugins/docker
    dockerfile: docker/Dockerfile
    environment:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    settings:
      repo: weweadsl/helloworld
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
#      target: production
#      tags: latest
      auto_tag: true

  - name: testing2
    pull: never
    image: ubuntu
    commands:
      - echo "test111"
      - echo "test222"
      - echo $TEST

#  - name: publish
#    image: plugins/gcr
#    settings:
#      repo: project/foo
#      tags: latest
#      json_key:
#        from_secret: google_credentials
#
#  - name: build-image
#    image: plugins/docker
#    settings:
#      repo: weweadsl/helloworld
#      target: production
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password
#      tags: ${DRONE_TAG}



image_pull_secrets:
  - dockerconfigjson
