version: '2'

services:
  drone-server:
    image: drone/drone:1
    ports:
      - 8080:80
    volumes:
      - ./:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST=https://73b380f42aad.ngrok.io
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET="123456"

      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=5d4d0d2b9781aa5e8198
      - DRONE_GITHUB_CLIENT_SECRET=e30354e170d1089bb9a5c33d8776825918061b26

      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  drone-agent:
    image: drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET="123456"
      - DRONE_RUNNER_CAPACITY=3