apiVersion: v1
kind: Service
metadata:
  namespace: hello
  name: hello-example
  labels:
    app: hello-example
spec:
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-example